### PR TITLE
fixed link in readme

### PR DESCRIPTION
**Pull request by manumaticx**

### CODE REVIEW

**Comment by manumaticx** [comment]
sorry, duplicates #10

**Comment by johnnyman727** [comment]
@manumaticx we haven't heard back from the other contributor in a while. If you can sign [our CLA](http://dojofoundation.org/about/claForm), I'd be happy to merge.

**Comment by manumaticx** [comment]
@johnnyman727 done!

**Comment by johnnyman727** [comment]
Thanks!

**Pull request merged**
